### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by polaris1119** [johntech-o/iphelper#1]
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/johntech-o/iphelper.(_IpStore).parseBodyLine(0xc8201299d0, 0xc82042d6b4, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
    github.com/johntech-o/iphelper/iphelper.go:248 +0xfc5
github.com/johntech-o/iphelper.(_IpStore).paseBody(0xc8201299d0, 0x0, 0x0)
    github.com/johntech-o/iphelper/iphelper.go:176 +0x19f
github.com/johntech-o/iphelper.(*IpStore).parseStore(0xc8201299d0, 0xc820116900, 0x2e)
    github.com/johntech-o/iphelper/iphelper.go:139 +0x577
github.com/johntech-o/iphelper.NewIpStore(0xc820116900, 0x2e, 0x22)
    github.com/johntech-o/iphelper/iphelper.go:43 +0x12b

**Comment by johntech-o** [comment]
bug fix
